### ISSUE TITLE
[resource][template] template update

### ISSUE THREAD

**Issue by treywelsh** [OpenNebula/terraform-provider-opennebula#220]
For a template resource it's possible to add a new key, to update an existing key, but it's not possible to remove a key. This is easily visible playing with the content of the `tags` section.

This problem has been identified in #218 

Note: in case it helps, the VM `user_template` section management has been reworked in #206

**Comment by Cookiiiies** [comment]
I played a little bit around but it seems that in first instance not the `resourceOpennebulaTemplateUpdate` is the problem. It's seems like the provider didn't recognize at all that there are changes. But I couldn't identify the code that lead to this problem. The `resourceOpennebulaTemplateRead` and `resourceOpennebulaTemplateExists` seems to work. 
In first instance, I thought it's related to the `flattenTemplate` function. But again, this seems not to be the root of the problem. 
Anyone has hint or a similar behavior before?

**Comment by treywelsh** [comment]
As you can see I just submitted a PR with additional details. It works to delete a key but it still needs to be tested to ensure that there is no other problems.

You may be confused in your test due to a mix of problems in the provider, and design decision that you may be not aware of.
I don't know how you are testing the provider so I'll show you how I'm doing.

By the way, you may need to understand the XML-RPC API, here the template update method:
https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#one-template-update
As you can see there is an update type parameter, which impact heavily how the update method work.

So first I'll show you that `tags` part has a problem, then I'll test some other attributes.
Feel free to comment/criticize If I miss something, or to show the exact test you are doing to help me to give you an accurate answer.

To see what's happening inside the provider method, I redirect logging in a file:
```
TF_LOG=TRACE TF_LOG_PATH=terraform.log terraform apply
```

Then I add some printing code:
```
	if d.HasChange("tags") {
		tagsInterface := d.Get("tags").(map[string]interface{})
		for k, v := range tagsInterface {
			tpl.Template.Del(strings.ToUpper(k))
			tpl.Template.AddPair(strings.ToUpper(k), v.(string))
		}

		log.Printf("[DEBUG] tags update: %s", tpl.Template.String())

		err = tc.Update(tpl.Template.String(), 1)
		if err != nil {
			return err
		}
	}
```

So first I apply this:
```
resource "opennebula_template" "template" {
  name        = "terra-tpl"
  permissions = "660"
  group       = "oneadmin"
  cpu         = "0.5"
  vcpu        = "1"
  memory      = "512"
  description = "VM created for provider acceptance tests"

  context = {
    dns_hostname = "yes"
    network      = "YES"
  }

  graphics {
    keymap = "en-us"
    listen = "0.0.0.0"
    type   = "VNC"
  }

  os {
    arch = "x86_64"
    boot = ""
  }

  tags = {
    env      = "prod"
    customer = "test"
  }

  sched_requirements = "FREE_CPU > 50"

  user_inputs = {
    BLOG_TITLE = "M|text|Blog Title"
  }

}
```

then I play with `tags` content:

I add a key:
```
  tags = {
    ...
    test = "test"
  }

```

Here is what's the provider submit to the template update method of OpenNebula (take a look at XML-RPC documentation for details on the API):
```
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: 2022/02/18 10:46:02 [DEBUG] tags update: CONTEXT=[
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     DNS_HOSTNAME="yes",
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     NETWORK="YES" ]
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: CPU="0.500000"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: DESCRIPTION="VM created for provider acceptance tests"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: GRAPHICS=[
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     KEYMAP="en-us",
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     LISTEN="0.0.0.0",
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     TYPE="VNC" ]
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: MEMORY="512"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: OS=[
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     ARCH="x86_64",
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     BOOT="" ]
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: SCHED_REQUIREMENTS="FREE_CPU > 50"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: USER_INPUTS=[
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula:     BLOG_TITLE="M|text|Blog Title" ]
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: VCPU="1"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: TEST="test"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: CUSTOMER="test"
2022-02-18T10:46:02.505+0100 [DEBUG] provider.terraform-provider-opennebula: ENV="prod"
```
It's ok, ONE should receive the `TEST` key

Now I update the key associated value:
```
  tags = {
    ...
    test = "test2"
  }

```

the result:
```
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: 2022/02/18 10:49:02 [DEBUG] ==== merge tags: CONTEXT=[
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     DNS_HOSTNAME="yes",
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     NETWORK="YES" ]
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: CPU="0.500000"
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: DESCRIPTION="VM created for provider acceptance tests"
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: GRAPHICS=[
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     KEYMAP="en-us",
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     LISTEN="0.0.0.0",
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     TYPE="VNC" ]
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: MEMORY="512"
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: OS=[
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     ARCH="x86_64",
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula:     BOOT="" ]
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: SCHED_REQUIREMENTS="FREE_CPU > 50"
2022-02-18T10:49:02.099+0100 [DEBUG] provider.terraform-provider-opennebula: USER_INPUTS=[
2022-02-18T10:49:02.100+0100 [DEBUG] provider.terraform-provider-opennebula:     BLOG_TITLE="M|text|Blog Title" ]
2022-02-18T10:49:02.100+0100 [DEBUG] provider.terraform-provider-opennebula: VCPU="1"
2022-02-18T10:49:02.100+0100 [DEBUG] provider.terraform-provider-opennebula: CUSTOMER="test"
2022-02-18T10:49:02.100+0100 [DEBUG] provider.terraform-provider-opennebula: ENV="prod"
2022-02-18T10:49:02.100+0100 [DEBUG] provider.terraform-provider-opennebula: TEST="test2"
```
It's ok, ONE should receive the updated `TEST` key

but if I remove the test key, it's still here:
```
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula: 2022/02/18 10:52:49 [DEBUG] ==== merge tags: CONTEXT=[
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula:     DNS_HOSTNAME="yes",
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula:     NETWORK="YES" ]
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula: CPU="0.500000"
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula: DESCRIPTION="VM created for provider acceptance tests"
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula: GRAPHICS=[
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula:     KEYMAP="en-us",
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula:     LISTEN="0.0.0.0",
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula:     TYPE="VNC" ]
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula: MEMORY="512"
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula: OS=[
2022-02-18T10:52:49.360+0100 [DEBUG] provider.terraform-provider-opennebula:     ARCH="x86_64",
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula:     BOOT="" ]
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula: SCHED_REQUIREMENTS="FREE_CPU > 50"
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula: TEST="test2"
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula: USER_INPUTS=[
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula:     BLOG_TITLE="M|text|Blog Title" ]
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula: VCPU="1"
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula: CUSTOMER="test"
2022-02-18T10:52:49.361+0100 [DEBUG] provider.terraform-provider-opennebula: ENV="prod"
```
So there is a problem in the update code for tags, the test key shouldn't be listed anymore.

If you apply again, terraform won't see a diff anymore due to the way we are reading the `tags` part.
In brief, the `tags` reading part only read keys that are listed on the tf file side. It's a design decision that we took at first because of the dynamic content of the tags part.
If not sure I'm clear here ?

I made similar test with the `description` attribute and it seems that there is no problems with it.

For CPU, VCPU... as you know there is no reading code, no update code, so we also have to add there parts.

**Comment by treywelsh** [comment]
I spotted an other problem, also similar to the one I fixed in the VM template in #206 
Make the same test of my comment above, but replace the sched_requirements with:
```
sched_requirements = "CLUSTER_ID!=\\\"123\\\""
```
If you play with tags keys, this error should occur:
```
│ Error: OpenNebula error [INTERNAL]: [one.template.update] Cannot update template. Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 1009860195, columns 286:297
```
It's an escaping problem in the provider due to the double quote chars. I'll update #222 accordingly.

**Comment by Cookiiiies** [comment]
thank you @treywelsh  for your detailed answer. I did it in a similar manner.

I did the following to check/test: 
`terraform apply`: (will create new)
```
resource "opennebula_template" "template" {
  name = "terratplupdate"
  permissions = "642"
  group = "oneadmin"

  cpu = "1"
  vcpu = "1"
  memory = "768"

  context = {
    dns_hostname = "yes"
    network = "YES"
  }

  graphics {
    keymap = "en-us"
    listen = "0.0.0.0"
    type = "VNC"
  }

  os {
    arch = "x86_64"
    boot = ""
  }

  tags = {
    env = "dev"
    customer = "test"
    version = "2"
  }
}
```

`terraform apply`: (update)
```
resource "opennebula_template" "template" {
  name = "terratplupdate"
}
```
After the update, the resource in opennebula still exists with all the attributes (inside ui; will test with api soon)  

```
CONTEXT = [
  DNS_HOSTNAME = "yes",
  NETWORK = "YES" ]
CPU = "1.000000"
CUSTOMER = "test"
ENV = "dev"
GRAPHICS = [
  KEYMAP = "en-us",
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
MEMORY = "768"
OS = [
  ARCH = "x86_64",
  BOOT = "" ]
VCPU = "1"
VERSION = "2"
```
 

So nothing seems to change. I don't know if this is something regarding to my setup or a general challenge. 
Could not yet test your provided code. So I don't know if this behavior persist after your MR.

**Comment by treywelsh** [comment]
My PR won't fix all of this, we need to add update code per key to remove them.

There is still some missing parts in the code that may seems obvious, but we didn't wrote it from scratch and it means that we just didn't need to delete these keys until now. I work in a company that use the provider in it's own way so we didn't make an inventory of all missing parts. When we see/needs something we improve the provider.

To keep the scope restricted to some code around parts I updated recently, in my PR, I only fixed deletion of some keys like the ones in the `tags` section, `sched_requirements` etc. So for instance with my last PR, in your test, the ENV, CUSTOMER, VERSION keys should be removed.
I think we should open an issue per resource to list what's missing. This may be part of the 0.5.0 milestone, why not (and help would be appreciated, there is still a lot of work to do).
